# casc.yaml

jenkins:
  systemMessage: "Welcome to Jenkins!\n\n"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  globalNodeProperties:
    - envVars:
        env:
          - key: "JENKINS_SEED_JOB_REPO_URL"
            value: "${JENKINS_SEED_JOB_REPO_URL}"
unclassified:
  location:
    url: "${JENKINS_LOCATION_URL}"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
jobs:
  - file: /usr/local/seed-job.groovy
  - script: >
      freeStyleJob("seed-job") {
        description("Seed Job")
        displayName("Seed Job")
        scm {
            git {
                remote {
                    url("${JENKINS_SEED_JOB_REPO_URL}")
                }
                branch("*/main")
            }
        }
        steps {
            jobDsl {
                removedJobAction("DELETE")
                removedViewAction("DELETE")
                targets("**/folder.groovy\n**/job.groovy")
            }
        }
        triggers {
            gitHubPushTrigger()
        }
      }
credentials:
  system:
    domainCredentials:
      - credentials:
          - gitHubApp:
              id: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_ANDREWJDAWES_ID}"
              # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
              appID: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_ANDREWJDAWES_APP_ID}"
              description: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_ANDREWJDAWES_DESCRIPTION}"
              # https://stackoverflow.com/questions/67494516/with-ansible-how-do-i-write-a-private-key-to-a-text-file-without-losing-the-lef
              privateKey: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_ANDREWJDAWES_PRIVATE_KEY}"
          - gitHubApp:
              id: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_CODEKAIZEN_ID}"
              # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
              appID: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_CODEKAIZEN_APP_ID}"
              description: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_CODEKAIZEN_DESCRIPTION}"
              # https://stackoverflow.com/questions/67494516/with-ansible-how-do-i-write-a-private-key-to-a-text-file-without-losing-the-lef
              privateKey: "${JENKINS_CREDENTIAL_JENKINS_GITHUB_CODEKAIZEN_PRIVATE_KEY}"
